fastqc:

macs2:
        --gsize: 11250000000

cutadapt:
        -a: CTGTCTCTTATACACATCT
        -A: CTGTCTCTTATACACATCT
        -q: 20
        --minimum-length: 36

qc_report:
        bsgenome: BSgenome.Drerio.UCSC.danRer10
        txdb: TxDb.Drerio.UCSC.danRer10.refGene
        nchr: 25
