fastqc:

macs2:
        --gsize: mm 

cutadapt:
        -a: CTGTCTCTTATACACATCT
        -A: CTGTCTCTTATACACATCT
        -q: 20
        --minimum-length: 36

qc_report:
        bsgenome: BSgenome.Mmusculus.UCSC.mm10
        txdb: TxDb.Mmusculus.UCSC.mm10.knownGene
        nchr: 20
